/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/spot.glb -t -r public -o src/components/Spot.tsx 
Author: 3dmodelsmith (https://sketchfab.com/3dmodelsmith)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boston-dynamics-robot-spot-71354fd599e34db898a7d083851b792a
Title: Boston Dynamics robot spot
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: any
  materials: any
}

export function Spot(props: any) {
  const { nodes, materials } = useGLTF('/spot.glb') as GLTFResult
  const group = useRef<THREE.Group>(null)

  // State to manage hover effects
  const [hovered, setHovered] = useState(false)

  // Smooth floating animation
  useFrame((state) => {
    if (!group.current) return;
    const t = state.clock.getElapsedTime();
    group.current.position.y = Math.sin(t) * 0.1;

    // Add slight rotation based on mouse position
    const targetX = (state.pointer.x * Math.PI) / 10;
    const targetY = (state.pointer.y * Math.PI) / 10;

    group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, -targetY, 0.1);
    group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, -targetX, 0.1);

    // Scale up slightly when hovered
    const targetScale = hovered ? 1.05 : 1;
    group.current.scale.setScalar(THREE.MathUtils.lerp(group.current.scale.x, targetScale, 0.1));
  });

  const handlePointerOver = () => {
    document.body.style.cursor = 'pointer';
    setHovered(true);
  };

  const handlePointerOut = () => {
    document.body.style.cursor = 'auto';
    setHovered(false);
  };

  const handleClick = (e: any) => {
    e.stopPropagation();
    // Scroll to the programs section
    const programsSection = document.getElementById('programs');
    if (programsSection) {
      programsSection.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onPointerOver={handlePointerOver}
      onPointerOut={handlePointerOut}
      onClick={handleClick}
    >
      <group position={[0, 2.498, 0.266]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.016']} />
      </group>
      <group position={[0, 2.192, -0.113]}>
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.012']} position={[0.515, 0.136, 0.265]} />
      </group>
      <group position={[0, 2.376, -1.985]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.010']} position={[0, -0.062, 0.228]} />
      </group>
      <group position={[-0.03, 2.399, 1.478]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_48.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_49.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Material.017']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.012']} position={[0.163, 2.329, -1.857]} rotation={[-0.417, 0.319, 0.006]} scale={[1.001, 1.033, 1.006]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.012']} position={[-0.165, 2.322, -1.842]} rotation={[-0.384, -0.161, 0]} scale={0.243} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.009']} position={[-0.148, 2.293, -1.867]} rotation={[-0.384, -0.161, 0]} scale={0.243} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.010']} position={[0, 2.331, -0.209]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.015']} position={[0.626, 1.759, 1.706]} rotation={[-0.809, 0, 0]} scale={0.09} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.010']} position={[0, 2.043, -0.734]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.010']} position={[0, 2.107, 0.942]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Material} position={[0.163, 2.329, -1.857]} rotation={[-0.417, 0.319, 0.006]} scale={[1.001, 1.033, 1.006]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.004']} position={[0.636, 1.515, 2.006]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.004']} position={[0.827, 2.156, 1.523]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.003']} position={[0, 2.352, -0.013]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.007']} position={[0, 2.436, 1.057]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.008']} position={[0, 2.394, 0.937]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials['Material.008']} position={[0.038, 2.339, -1.501]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['Material.010']} position={[0, 2.043, 0.5]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials['Material.002']} position={[0, 2.043, -0.747]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials['Material.021']} position={[0.827, 2.156, -0.901]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['Material.021']} position={[0.636, 1.515, -0.418]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials['Material.020']} position={[0.626, 1.759, -0.717]} rotation={[-0.809, 0, 0]} scale={0.09} />
    </group>
  )
}

useGLTF.preload('/spot.glb')
